apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
  labels:
    app: elasticcloud
spec:
  version: 7.5.2
  http:
    service:
      spec:
        type: NodePort
        ports:
          - name: https
            port: 9200
            targetPort: 9200
            protocol: TCP
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
